<?php $presets["skin16c"] = array (
  'preset' => 'skin16c',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin16c.header-logo-regular.png?w=67&h=79',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin16c.header-logo-hd.png?w=134&h=158',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin16b.bottom-bar-logo-regular.png?w=29&h=33',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin16b.bottom-bar-logo-hd.png?w=58&h=66',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin16c.general-floating-menu-logo-regular.png?w=29&h=33',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin16c.general-floating-menu-logo-hd.png?w=58&h=66',
    1 => 0,
  ),
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-content_width' => '1188px',
  'general-layout' => 'boxed',
  'general-box_width' => '1220px',
  'general-boxed_bg_color' => '#ffffff',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16c.general-boxed-bg-image.jpg',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '0',
  'general-responsive' => '1',
  'general-accent_bg_color' => '#d4a970',
  'general-border_radius' => 0,
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-smooth_scroll' => 'off',
  'fonts-font_family' => 'Open Sans&subset=latin-ext',
  'fonts-normal_size' => 13,
  'fonts-normal_size_line_height' => 22,
  'fonts-small_size' => 12,
  'fonts-small_size_line_height' => 20,
  'fonts-big_size' => 14,
  'fonts-big_size_line_height' => 24,
  'fonts-h1_font_family' => 'Raleway:500',
  'fonts-h1_font_size' => 48,
  'fonts-h1_line_height' => 54,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Raleway:500',
  'fonts-h2_font_size' => 36,
  'fonts-h2_line_height' => 42,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Raleway:500',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Raleway:600',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 24,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Raleway:600',
  'fonts-h5_font_size' => 15,
  'fonts-h5_line_height' => 23,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Raleway:600',
  'fonts-h6_font_size' => 13,
  'fonts-h6_line_height' => 23,
  'fonts-h6_uppercase' => '1',
  'buttons-s_font_family' => 'Raleway:600',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 28,
  'buttons-m_font_family' => 'Raleway:700',
  'buttons-m_font_size' => 13,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 37,
  'buttons-l_font_family' => 'Raleway:600',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'top_bar-bg_color' => '#ececec',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#b2b2b2',
  'header-bg_color' => '#ffffff',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#dd3333',
  'header-transparent_bg_opacity' => 0,
  'header-bg_height' => 70,
  'header-layout' => 'center',
  'header-show_floating_menu' => '1',
  'content-headers_color' => '#3a3a3a',
  'content-primary_text_color' => '#8e8e8e',
  'stripes-stripe_1_color' => '#f5f5f5',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#333333',
  'stripes-stripe_1_text_color' => '#8e8e8e',
  'stripes-stripe_2_color' => '#ffffff',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#333333',
  'stripes-stripe_2_text_color' => '#8e8e8e',
  'stripes-stripe_3_color' => '#141414',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin16c.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#ffffff',
  'stripes-stripe_3_text_color' => '#f4f4f4',
  'sidebar-headers_color' => '#3a3a3a',
  'sidebar-primary_text_color' => '#8e8e8e',
  'footer-bg_color' => '#333333',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-headers_color' => '#f5f5f5',
  'footer-primary_text_color' => '#888888',
  'bottom_bar-bg_color' => '#3d3d3d',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#888888',
  'bottom_bar-credits' => '1',
  'top_bar-font_size' => 'small',
  'top_bar-bg_mode' => 'fullwidth_line',
  'menu-font_family' => 'Raleway:600',
  'menu-font_size' => 14,
  'menu-font_uppercase' => '1',
  'menu-next_level_indicator' => '1',
  'menu-font_color' => '#898989',
  'menu-hover_font_color_mode' => 'color',
  'menu-hover_font_color' => '#2d2d2d',
  'menu-hover_font_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#0ce6ab',
  ),
  'menu-decoration_style' => 'brackets',
  'menu-hover_decoration_color_mode' => 'accent',
  'menu-hover_decoration_color' => '#ffffff',
  'menu-hover_decoration_color_gradient' => 
  array (
    0 => '#eeee22',
    1 => '#0bed56',
  ),
  'top_bar-paddings' => 9,
  'menu-iconfont_size' => 14,
  'menu-items_distance' => 29,
  'submenu-font_family' => 'Raleway:500',
  'submenu-font_size' => 12,
  'submenu-font_uppercase' => false,
  'submenu-next_level_indicator' => '1',
  'submenu-font_color' => '#a0a0a0',
  'submenu-hover_font_color_mode' => 'accent',
  'submenu-hover_font_color' => '#ffffff',
  'submenu-hover_font_color_gradient' => 
  array (
    0 => '#81d742',
    1 => '#eeee22',
  ),
  'submenu-iconfont_size' => 12,
  'submenu-items_distance' => 16,
  'submenu-bg_color' => '#ffffff',
  'submenu-bg_opacity' => 100,
  'submenu-bg_width' => 230,
  'general-accent_color_mode' => 'color',
  'general-accent_bg_color_gradient' => 
  array (
    0 => '#75539e',
    1 => '#c25b7c',
  ),
  'header-left_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'phone',
      1 => 'skype',
      2 => 'email',
    ),
    'top_bar_right' => 
    array (
      0 => 'cart',
      1 => 'search',
      2 => 'social_icons',
    ),
  ),
  'header-center_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'phone',
      1 => 'skype',
      2 => 'working_hours',
      3 => 'search',
      4 => 'cart',
    ),
  ),
  'header-near_logo_font_size' => 'big',
  'header-near_logo_bg_color' => '#828282',
  'header-classic_layout_elements' => 
  array (
    'logo_area' => 
    array (
      0 => 'text_area',
      1 => 'social_icons',
    ),
    'nav_area' => 
    array (
      0 => 'search',
      1 => 'cart',
    ),
  ),
  'header-side_paddings' => 30,
  'header-side_position' => 'left',
  'header-side_menu_align' => 'left',
  'header-side_layout_elements' => 
  array (
    'top' => 
    array (
      0 => 'phone',
      1 => 'search',
    ),
    'bottom' => 
    array (
      0 => 'social_icons',
      1 => 'text_area',
    ),
  ),
  'header-woocommerce_cart_icon' => '1',
  'header-left_layout_fullwidth' => false,
  'header-woocommerce_cart_caption' => 'Cart',
  'header-woocommerce_counter_bg_mode' => 'accent',
  'header-woocommerce_counter_bg_color' => '#afafaf',
  'header-woocommerce_counter_bg_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#81d742',
  ),
  'header-soc_icon_color' => '#c9c9c9',
  'header-soc_icon_hover_color' => '#999999',
  'header-logo_padding_top' => 32,
  'header-logo_padding_bottom' => 4,
  'float_menu-height' => 54,
  'float_menu-transparency' => 100,
  'header-side_menu_width' => '300px',
  'header-side_menu_lines' => '1',
  'header-side_menu_lines_color' => '#eeeeee',
  'header-classic_menu_bg_mode' => 'fullwidth_line',
  'header-classic_menu_bg_color' => '#ececec',
  'header-center_menu_bg_mode' => 'disabled',
  'header-center_menu_bg_color' => '#ececec',
  'header-soc_icon_bg_color_mode' => 'disabled',
  'header-soc_icon_bg_color' => '#ffffff',
  'header-soc_icon_bg_color_gradient' => 
  array (
    0 => '#8224e3',
    1 => '#43d8c7',
  ),
  'header-soc_icon_hover_bg_color_mode' => 'color',
  'header-soc_icon_hover_bg_color' => '#ffffff',
  'header-soc_icon_hover_bg_color_gradient' => 
  array (
    0 => '#ef5689',
    1 => '#a6ff16',
  ),
  'general-title_size' => 'h2',
  'general-title_height' => 110,
  'general-title_bg_mode' => 'background',
  'general-title_bg_color' => '#f5f5f5',
  'general-breadcrumbs_color' => '#b5b5b5',
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-title_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-title_bg_fullscreen' => false,
  'general-title_bg_fixed' => false,
  'general-title_bg_parallax' => '',
  'buttons-style' => 'flat',
  'buttons-color_mode' => 'color',
  'buttons-color' => '#919191',
  'buttons-color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#3a892a',
  ),
  'buttons-s_border_radius' => 0,
  'buttons-m_border_radius' => 0,
  'buttons-l_border_radius' => 0,
  'general-title_color' => '#3a3a3a',
  'image_hover-style' => 'blur',
  'image_hover-color_mode' => 'color',
  'image_hover-color' => '#303030',
  'image_hover-color_gradient' => 
  array (
    0 => '#8224e3',
    1 => '#eeee22',
  ),
  'image_hover-opacity' => 50,
  'image_hover-with_icons_opacity' => 86,
  'general-next_prev_in_album' => '1',
  'general-show_back_button_in_album' => '1',
  'general-album_back_button_target_page_id' => 16237,
  'general-album_meta_on' => '1',
  'general-album_meta_date' => '1',
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'general-boxed_bg_fixed' => '1',
  'sidebar-width' => 28,
  'sidebar-vertical_distance' => 82,
  'sidebar-divider-vertical' => '1',
  'sidebar-divider-horizontal' => '1',
  'header-mobile-first_switch-after' => 850,
  'header-mobile-first_switch-logo' => 'mobile',
  'header-mobile-second_switch-after' => 400,
  'header-mobile-second_switch-logo' => 'mobile',
  'header-mobile-menu_color' => 'accent',
  'header-mobile-menu_color-background' => '#81d742',
  'header-mobile-menu_color-text' => '#000000',
  'general-mobile_logo-regular' => 
  array (
    0 => '/inc/presets/images/full/skin16c.general-mobile-logo-regular.png?w=67&h=79',
    1 => 0,
  ),
  'general-mobile_logo-hd' => 
  array (
    0 => '/inc/presets/images/full/skin16c.general-mobile-logo-hd.png?w=134&h=158',
    1 => 0,
  ),
  'general-mobile_logo-padding_top' => '20',
  'general-mobile_logo-padding_bottom' => '20',
  'footer-style' => 'solid_background',
  'footer-slide-out-mode' => '0',
  'footer-paddings-top-bottom' => 50,
  'footer-paddings-columns' => 22,
  'bottom_bar-style' => 'solid_background',
  'footer-collapse_after' => 970,
  'header-background' => 'normal',
  'header-menu_text_color_mode' => 'theme',
  'header-menu_hover_color_mode' => 'theme',
  'header-menu_top_bar_color_mode' => 'theme',
  'header-bg_opacity' => 100,
  'header-bg_fullscreen' => false,
  'header-bg_fixed' => false,
  'header-center_menu_bg_opacity' => 100,
  'header-classic_menu_bg_opacity' => 100,
  'header-side_menu_lines_opacity' => 100,
  'general-bg_fixed' => false,
  'header-style' => 'disabled',
  'general-responsiveness-treshold' => 970,
  'header-side_menu_dropdown_style' => 'side',
); ?>