<?php $presets["skin09s"] = array (
  'preset' => 'skin09s',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin09s.header-logo-regular.png?w=89&h=104',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin09s.header-logo-hd.png?w=178&h=208',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin09s.bottom-bar-logo-regular.png?w=29&h=33',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin09s.bottom-bar-logo-hd.png?w=58&h=66',
    1 => 0,
  ),
  'general-floating_menu_show_logo' => '0',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '',
    1 => 0,
  ),
  'general-bg_color' => '#f8f7f7',
  'general-bg_opacity' => 100,
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-content_width' => '1188px',
  'general-layout' => 'boxed',
  'general-box_width' => '1200px',
  'general-boxed_bg_color' => '#f8f7f7',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin09s.general-boxed-bg-image.jpg',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-show_titles' => '1',
  'general-title_align' => 'left',
  'general-show_breadcrumbs' => '1',
  'general-responsive' => '1',
  'general-accent_bg_color' => '#9d719f',
  'general-border_radius' => 0,
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-smooth_scroll' => 'off',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 13,
  'fonts-normal_size_line_height' => 22,
  'fonts-small_size' => 12,
  'fonts-small_size_line_height' => 20,
  'fonts-big_size' => 14,
  'fonts-big_size_line_height' => 24,
  'fonts-h1_font_family' => 'Source Sans Pro:600',
  'fonts-h1_font_size' => 48,
  'fonts-h1_line_height' => 55,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Source Sans Pro:600',
  'fonts-h2_font_size' => 38,
  'fonts-h2_line_height' => 44,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Source Sans Pro:600',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Source Sans Pro:600',
  'fonts-h4_font_size' => 20,
  'fonts-h4_line_height' => 26,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Source Sans Pro:600',
  'fonts-h5_font_size' => 17,
  'fonts-h5_line_height' => 24,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Source Sans Pro:600',
  'fonts-h6_font_size' => 16,
  'fonts-h6_line_height' => 24,
  'fonts-h6_uppercase' => false,
  'buttons-s_font_family' => 'Source Sans Pro:600',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 27,
  'buttons-m_font_family' => 'Source Sans Pro:600',
  'buttons-m_font_size' => 15,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 38,
  'buttons-l_font_family' => 'Source Sans Pro:600',
  'buttons-l_font_size' => 19,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 48,
  'top_bar-bg_color' => '#eaeaea',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#b9b5b8',
  'header-bg_color' => '#ffffff',
  'header-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-transparent_bg_color' => '#ffffff',
  'header-transparent_bg_opacity' => 36,
  'header-bg_height' => 120,
  'header-layout' => 'side',
  'header-show_floating_menu' => '1',
  'content-headers_color' => '#3f293f',
  'content-primary_text_color' => '#8b8389',
  'stripes-stripe_1_color' => '#f1eff0',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#3f293f',
  'stripes-stripe_1_text_color' => '#8b8389',
  'stripes-stripe_2_color' => '#f8f7f7',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_2_headers_color' => '#3f293f',
  'stripes-stripe_2_text_color' => '#8b8389',
  'stripes-stripe_3_color' => '#2b1e2b',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin09s.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_3_headers_color' => '#f9f6f9',
  'stripes-stripe_3_text_color' => '#f9f6f9',
  'sidebar-headers_color' => '#3f293f',
  'sidebar-primary_text_color' => '#8b8389',
  'footer-bg_color' => '#2c1c2c',
  'footer-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-headers_color' => '#f9f6f9',
  'footer-primary_text_color' => '#928992',
  'bottom_bar-bg_color' => '#3f293f',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#f9f6f9',
  'bottom_bar-credits' => '1',
  'top_bar-font_size' => 'small',
  'top_bar-bg_mode' => 'disabled',
  'menu-font_family' => 'Source Sans Pro:600',
  'menu-font_size' => 16,
  'menu-font_uppercase' => false,
  'menu-next_level_indicator' => '1',
  'menu-font_color' => '#423140',
  'menu-hover_font_color_mode' => 'accent',
  'menu-hover_font_color' => '#423140',
  'menu-hover_font_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#0ce6ab',
  ),
  'menu-decoration_style' => 'disabled',
  'menu-hover_decoration_color_mode' => 'accent',
  'menu-hover_decoration_color' => '#b188b6',
  'menu-hover_decoration_color_gradient' => 
  array (
    0 => '#eeee22',
    1 => '#0bed56',
  ),
  'top_bar-paddings' => 9,
  'menu-iconfont_size' => 14,
  'menu-items_distance' => 24,
  'submenu-font_family' => 'Arial',
  'submenu-font_size' => 12,
  'submenu-font_uppercase' => false,
  'submenu-next_level_indicator' => '1',
  'submenu-font_color' => '#b9b5b8',
  'submenu-hover_font_color_mode' => 'accent',
  'submenu-hover_font_color' => '#b188b6',
  'submenu-hover_font_color_gradient' => 
  array (
    0 => '#81d742',
    1 => '#eeee22',
  ),
  'submenu-iconfont_size' => 12,
  'submenu-items_distance' => 7,
  'submenu-bg_color' => '#ffffff',
  'submenu-bg_opacity' => 100,
  'submenu-bg_width' => 230,
  'general-accent_color_mode' => 'color',
  'general-accent_bg_color_gradient' => 
  array (
    0 => '#4c3c51',
    1 => '#69496c',
  ),
  'header-left_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'phone',
      1 => 'skype',
      2 => 'email',
    ),
    'top_bar_right' => 
    array (
      0 => 'cart',
      1 => 'search',
    ),
    'nav_area' => 
    array (
      0 => 'social_icons',
    ),
  ),
  'header-center_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'email',
      1 => 'phone',
      2 => 'skype',
      3 => 'search',
      4 => 'cart',
    ),
    'nav_area' => 
    array (
      0 => 'social_icons',
    ),
  ),
  'header-near_logo_font_size' => 'big',
  'header-near_logo_bg_color' => '#878787',
  'header-classic_layout_elements' => 
  array (
    'top_bar_left' => 
    array (
      0 => 'address',
    ),
    'top_bar_right' => 
    array (
      0 => 'text_area',
      1 => 'skype',
      2 => 'email',
    ),
    'logo_area' => 
    array (
      0 => 'phone',
      1 => 'search',
    ),
    'nav_area' => 
    array (
      0 => 'social_icons',
    ),
  ),
  'header-side_paddings' => 40,
  'header-side_position' => 'left',
  'header-side_menu_align' => 'left',
  'header-side_layout_elements' => 
  array (
    'bottom' => 
    array (
      0 => 'search',
      1 => 'cart',
      2 => 'social_icons',
    ),
  ),
  'header-woocommerce_cart_icon' => '1',
  'header-left_layout_fullwidth' => false,
  'header-woocommerce_cart_caption' => 'Cart',
  'header-woocommerce_counter_bg_mode' => 'accent',
  'header-woocommerce_counter_bg_color' => '#dd3333',
  'header-woocommerce_counter_bg_color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#81d742',
  ),
  'header-soc_icon_color' => '#b9b5b8',
  'header-soc_icon_hover_color' => '#9d719f',
  'header-logo_padding_top' => 40,
  'header-logo_padding_bottom' => 42,
  'float_menu-height' => 50,
  'float_menu-transparency' => 100,
  'header-side_menu_width' => '280px',
  'header-side_menu_lines' => '1',
  'header-side_menu_lines_color' => '#eeeeee',
  'header-classic_menu_bg_mode' => 'solid',
  'header-classic_menu_bg_color' => '#f2f2f2',
  'header-center_menu_bg_mode' => 'content_line',
  'header-center_menu_bg_color' => '#f4f4f4',
  'header-soc_icon_bg_color_mode' => 'disabled',
  'header-soc_icon_bg_color' => '#c9c1ca',
  'header-soc_icon_bg_color_gradient' => 
  array (
    0 => '#8224e3',
    1 => '#43d8c7',
  ),
  'header-soc_icon_hover_bg_color_mode' => 'disabled',
  'header-soc_icon_hover_bg_color' => '#855e86',
  'header-soc_icon_hover_bg_color_gradient' => 
  array (
    0 => '#ef5689',
    1 => '#a6ff16',
  ),
  'general-title_size' => 'h2',
  'general-title_height' => 100,
  'general-title_bg_mode' => 'content_line',
  'general-title_bg_color' => '#adadad',
  'general-breadcrumbs_color' => '#bdb8bc',
  'general-breadcrumbs_bg_color' => 'disabled',
  'general-title_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'no-repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'general-title_bg_fullscreen' => false,
  'general-title_bg_fixed' => false,
  'general-title_bg_parallax' => '',
  'buttons-style' => 'flat',
  'buttons-color_mode' => 'accent',
  'buttons-color' => '#81d742',
  'buttons-color_gradient' => 
  array (
    0 => '#dd3333',
    1 => '#3a892a',
  ),
  'buttons-s_border_radius' => 2,
  'buttons-m_border_radius' => 2,
  'buttons-l_border_radius' => 2,
  'general-title_color' => '#3f293f',
  'image_hover-style' => 'scale',
  'image_hover-color_mode' => 'color',
  'image_hover-color' => '#3f293f',
  'image_hover-color_gradient' => 
  array (
    0 => '#222222',
    1 => '#444444',
  ),
  'image_hover-opacity' => 60,
  'image_hover-with_icons_opacity' => 90,
  'general-next_prev_in_album' => '1',
  'general-show_back_button_in_album' => '1',
  'general-album_back_button_target_page_id' => 16237,
  'general-album_meta_on' => '1',
  'general-album_meta_date' => '1',
  'general-album_meta_author' => false,
  'general-album_meta_categories' => '1',
  'general-album_meta_comments' => false,
  'general-boxed_bg_fixed' => '1',
  'sidebar-width' => 28,
  'sidebar-vertical_distance' => 82,
  'sidebar-divider-vertical' => '1',
  'sidebar-divider-horizontal' => '1',
  'header-mobile-first_switch-after' => 1100,
  'header-mobile-first_switch-logo' => 'mobile',
  'header-mobile-second_switch-after' => 400,
  'header-mobile-second_switch-logo' => 'mobile',
  'header-mobile-menu_color' => 'accent',
  'header-mobile-menu_color-background' => '#f94dda',
  'header-mobile-menu_color-text' => '#000000',
  'general-mobile_logo-regular' => 
  array (
    0 => '/inc/presets/images/full/skin09s.general-mobile-logo-regular.png?w=67&h=79',
    1 => 0,
  ),
  'general-mobile_logo-hd' => 
  array (
    0 => '/inc/presets/images/full/skin09s.general-mobile-logo-hd.png?w=134&h=158',
    1 => 0,
  ),
  'general-mobile_logo-padding_top' => '20',
  'general-mobile_logo-padding_bottom' => '20',
  'footer-style' => 'solid_background',
  'footer-slide-out-mode' => '1',
  'footer-paddings-top-bottom' => 50,
  'footer-paddings-columns' => 22,
  'bottom_bar-style' => 'content_width_line',
  'footer-collapse_after' => 970,
  'header-background' => 'normal',
  'header-menu_text_color_mode' => 'theme',
  'header-menu_hover_color_mode' => 'theme',
  'header-menu_top_bar_color_mode' => 'theme',
  'header-bg_opacity' => 100,
  'header-bg_fullscreen' => false,
  'header-bg_fixed' => false,
  'header-center_menu_bg_opacity' => 100,
  'header-classic_menu_bg_opacity' => 100,
  'header-side_menu_lines_opacity' => 90,
  'general-bg_fixed' => false,
  'header-style' => 'solid_background',
  'general-responsiveness-treshold' => 970,
  'header-side_menu_dropdown_style' => 'down',
); ?>